"""LSP module for opencode."""

from opencode.lsp.index import (
    DocumentSymbol,
    Event,
    Range,
    Status,
    Symbol,
    SymbolKind,
    definition,
    diagnostic_pretty,
    diagnostics,
    document_symbol,
    has_clients,
    hover,
    implementation,
    incoming_calls,
    init,
    outgoing_calls,
    prepare_call_hierarchy,
    references,
    status,
    touch_file,
    workspace_symbol,
)
from opencode.lsp.server import (
    Handle,
    ServerInfo,
    nearest_root,
)

__all__ = [
    "DocumentSymbol",
    "Event",
    "Handle",
    "Range",
    "ServerInfo",
    "Status",
    "Symbol",
    "SymbolKind",
    "definition",
    "diagnostic_pretty",
    "diagnostics",
    "document_symbol",
    "has_clients",
    "hover",
    "implementation",
    "incoming_calls",
    "init",
    "nearest_root",
    "outgoing_calls",
    "prepare_call_hierarchy",
    "references",
    "status",
    "touch_file",
    "workspace_symbol",
]
