"""Permission module for opencode."""

from opencode.permission.index import (
    Event,
    PermissionInfo,
    PermissionReplied,
    RejectedError,
    ask,
    list_permissions,
    pending,
    respond,
)
from opencode.permission.next import (
    Action,
    CorrectedError,
    DeniedError,
    RejectedError as NextRejectedError,
    Reply,
    Request,
    Rule,
    ask as ask_next,
    disabled,
    evaluate,
    expand,
    from_config,
    list_requests,
    merge,
    reply,
)

__all__ = [
    "Action",
    "CorrectedError",
    "DeniedError",
    "Event",
    "NextRejectedError",
    "PermissionInfo",
    "PermissionReplied",
    "Reply",
    "RejectedError",
    "Request",
    "Rule",
    "ask",
    "ask_next",
    "disabled",
    "evaluate",
    "expand",
    "from_config",
    "list_permissions",
    "list_requests",
    "merge",
    "pending",
    "reply",
    "respond",
]
