"""Feature flags module for opencode."""

from __future__ import annotations

import os
from typing import Any


def _truthy(key: str) -> bool:
    """Check if environment variable is truthy."""
    value = os.environ.get(key, "").lower()
    return value in ("true", "1", "yes", "on")


def _number(key: str) -> int | None:
    """Parse environment variable as number."""
    value = os.environ.get(key)
    if not value:
        return None
    try:
        parsed = int(value)
        return parsed if parsed > 0 else None
    except ValueError:
        return None


# Core flags
OPENCODE_AUTO_SHARE = _truthy("OPENCODE_AUTO_SHARE")
OPENCODE_GIT_BASH_PATH = os.environ.get("OPENCODE_GIT_BASH_PATH")
OPENCODE_CONFIG = os.environ.get("OPENCODE_CONFIG")
OPENCODE_CONFIG_CONTENT = os.environ.get("OPENCODE_CONFIG_CONTENT")
OPENCODE_DISABLE_AUTOUPDATE = _truthy("OPENCODE_DISABLE_AUTOUPDATE")
OPENCODE_DISABLE_PRUNE = _truthy("OPENCODE_DISABLE_PRUNE")
OPENCODE_DISABLE_TERMINAL_TITLE = _truthy("OPENCODE_DISABLE_TERMINAL_TITLE")
OPENCODE_PERMISSION = os.environ.get("OPENCODE_PERMISSION")
OPENCODE_DISABLE_DEFAULT_PLUGINS = _truthy("OPENCODE_DISABLE_DEFAULT_PLUGINS")
OPENCODE_DISABLE_LSP_DOWNLOAD = _truthy("OPENCODE_DISABLE_LSP_DOWNLOAD")
OPENCODE_ENABLE_EXPERIMENTAL_MODELS = _truthy("OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
OPENCODE_DISABLE_AUTOCOMPACT = _truthy("OPENCODE_DISABLE_AUTOCOMPACT")
OPENCODE_DISABLE_MODELS_FETCH = _truthy("OPENCODE_DISABLE_MODELS_FETCH")
OPENCODE_DISABLE_CLAUDE_CODE = _truthy("OPENCODE_DISABLE_CLAUDE_CODE")
OPENCODE_DISABLE_CLAUDE_CODE_PROMPT = OPENCODE_DISABLE_CLAUDE_CODE or _truthy("OPENCODE_DISABLE_CLAUDE_CODE_PROMPT")
OPENCODE_DISABLE_CLAUDE_CODE_SKILLS = OPENCODE_DISABLE_CLAUDE_CODE or _truthy("OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
OPENCODE_DISABLE_EXTERNAL_SKILLS = OPENCODE_DISABLE_CLAUDE_CODE_SKILLS or _truthy("OPENCODE_DISABLE_EXTERNAL_SKILLS")
OPENCODE_FAKE_VCS = os.environ.get("OPENCODE_FAKE_VCS")
OPENCODE_SERVER_PASSWORD = os.environ.get("OPENCODE_SERVER_PASSWORD")
OPENCODE_SERVER_USERNAME = os.environ.get("OPENCODE_SERVER_USERNAME")

# Experimental flags
OPENCODE_EXPERIMENTAL = _truthy("OPENCODE_EXPERIMENTAL")
OPENCODE_EXPERIMENTAL_FILEWATCHER = _truthy("OPENCODE_EXPERIMENTAL_FILEWATCHER")
OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = _truthy("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
OPENCODE_EXPERIMENTAL_ICON_DISCOVERY = OPENCODE_EXPERIMENTAL or _truthy("OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")
OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = _truthy("OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
OPENCODE_ENABLE_EXA = _truthy("OPENCODE_ENABLE_EXA") or OPENCODE_EXPERIMENTAL or _truthy("OPENCODE_EXPERIMENTAL_EXA")
OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = _number("OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = _number("OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
OPENCODE_EXPERIMENTAL_OXFMT = OPENCODE_EXPERIMENTAL or _truthy("OPENCODE_EXPERIMENTAL_OXFMT")
OPENCODE_EXPERIMENTAL_LSP_TY = _truthy("OPENCODE_EXPERIMENTAL_LSP_TY")
OPENCODE_EXPERIMENTAL_LSP_TOOL = OPENCODE_EXPERIMENTAL or _truthy("OPENCODE_EXPERIMENTAL_LSP_TOOL")
OPENCODE_DISABLE_FILETIME_CHECK = _truthy("OPENCODE_DISABLE_FILETIME_CHECK")
OPENCODE_EXPERIMENTAL_PLAN_MODE = OPENCODE_EXPERIMENTAL or _truthy("OPENCODE_EXPERIMENTAL_PLAN_MODE")
OPENCODE_EXPERIMENTAL_MARKDOWN = _truthy("OPENCODE_EXPERIMENTAL_MARKDOWN")
OPENCODE_MODELS_URL = os.environ.get("OPENCODE_MODELS_URL")
OPENCODE_MODELS_PATH = os.environ.get("OPENCODE_MODELS_PATH")


# Dynamic properties (evaluated at access time)
class _DynamicFlag:
    """Dynamic flag that evaluates at access time."""
    
    @property
    def OPENCODE_DISABLE_PROJECT_CONFIG(self) -> bool:
        return _truthy("OPENCODE_DISABLE_PROJECT_CONFIG")
    
    @property
    def OPENCODE_CONFIG_DIR(self) -> str | None:
        return os.environ.get("OPENCODE_CONFIG_DIR")
    
    @property
    def OPENCODE_CLIENT(self) -> str:
        return os.environ.get("OPENCODE_CLIENT", "cli")


_dynamic = _DynamicFlag()
OPENCODE_DISABLE_PROJECT_CONFIG = _dynamic.OPENCODE_DISABLE_PROJECT_CONFIG
OPENCODE_CONFIG_DIR = _dynamic.OPENCODE_CONFIG_DIR
OPENCODE_CLIENT = _dynamic.OPENCODE_CLIENT


def get(key: str, default: Any = None) -> Any:
    """Get a flag value by key."""
    return globals().get(key, default)


def is_enabled(flag_name: str) -> bool:
    """Check if a flag is enabled."""
    value = globals().get(flag_name)
    if callable(value):
        return bool(value())
    return bool(value)


__all__ = [
    "OPENCODE_AUTO_SHARE",
    "OPENCODE_GIT_BASH_PATH",
    "OPENCODE_CONFIG",
    "OPENCODE_CONFIG_CONTENT",
    "OPENCODE_DISABLE_AUTOUPDATE",
    "OPENCODE_DISABLE_PRUNE",
    "OPENCODE_DISABLE_TERMINAL_TITLE",
    "OPENCODE_PERMISSION",
    "OPENCODE_DISABLE_DEFAULT_PLUGINS",
    "OPENCODE_DISABLE_LSP_DOWNLOAD",
    "OPENCODE_ENABLE_EXPERIMENTAL_MODELS",
    "OPENCODE_DISABLE_AUTOCOMPACT",
    "OPENCODE_DISABLE_MODELS_FETCH",
    "OPENCODE_DISABLE_CLAUDE_CODE",
    "OPENCODE_DISABLE_CLAUDE_CODE_PROMPT",
    "OPENCODE_DISABLE_CLAUDE_CODE_SKILLS",
    "OPENCODE_DISABLE_EXTERNAL_SKILLS",
    "OPENCODE_FAKE_VCS",
    "OPENCODE_SERVER_PASSWORD",
    "OPENCODE_SERVER_USERNAME",
    "OPENCODE_EXPERIMENTAL",
    "OPENCODE_EXPERIMENTAL_FILEWATCHER",
    "OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER",
    "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY",
    "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT",
    "OPENCODE_ENABLE_EXA",
    "OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS",
    "OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX",
    "OPENCODE_EXPERIMENTAL_OXFMT",
    "OPENCODE_EXPERIMENTAL_LSP_TY",
    "OPENCODE_EXPERIMENTAL_LSP_TOOL",
    "OPENCODE_DISABLE_FILETIME_CHECK",
    "OPENCODE_EXPERIMENTAL_PLAN_MODE",
    "OPENCODE_EXPERIMENTAL_MARKDOWN",
    "OPENCODE_MODELS_URL",
    "OPENCODE_MODELS_PATH",
    "OPENCODE_DISABLE_PROJECT_CONFIG",
    "OPENCODE_CONFIG_DIR",
    "OPENCODE_CLIENT",
    "get",
    "is_enabled",
]
